version: "3.8"

services:
  flask-demo:
    #build: ./flask
    build:
      context: ./flask
      dockerfile: Dockerfile.dev

    image: flask-demo:latest
    environment:
      - REDIS_HOST=redis-server
    networks:
      - demo-network
    ports:
      - 3004:5000

  redis-server:
    image: redis:latest
    networks:
      - demo-network

  

networks:
  demo-network: